language: java

jdk:
  - openjdk17

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: mvn deploy -B -DskipTests=true
  on:
    branch: master

cache:
  directories:
    - $HOME/.m2
